insert into membership (m_key, name, priority, duration) values ('b1', 'basic', 1, 24);
insert into membership (m_key, name, priority, duration) values ('b10', 'basic', 10, 48);
insert into membership (m_key, name, priority, duration) values ('m17', 'medium', 17, 2);
insert into membership (m_key, name, priority, duration) values ('m13', 'medium', 13, 30);
insert into membership (m_key, name, priority, duration) values ('m14', 'medium', 14, 35);
insert into membership (m_key, name, priority, duration) values ('p18', 'premium', 18, 96);
insert into membership (m_key, name, priority, duration) values ('m16', 'medium', 16, 43);
insert into membership (m_key, name, priority, duration) values ('b10', 'basic', 10, 48);
insert into membership (m_key, name, priority, duration) values ('b3', 'basic', 3, 27);
insert into membership (m_key, name, priority, duration) values ('b6', 'basic', 6, 29);


insert into product (name, cost, min_priory) values ('television', 0.44, 1);
insert into product (name, cost, min_priory) values ('espejo', 8.49, 2);
insert into product (name, cost, min_priory) values ('telefono', 6.62, 3);
insert into product (name, cost, min_priory) values ('laptop', 6.60, 4);
insert into product (name, cost, min_priory) values ('computadora', 7.55, 5);
insert into product (name, cost, min_priory) values ('cocina', 8.85, 6);
insert into product (name, cost, min_priory) values ('nevera', 9.75, 7);
insert into product (name, cost, min_priory) values ('lampara', 9.85, 8);
insert into product (name, cost, min_priory) values ('aire', 9.23, 9);
insert into product (name, cost, min_priory) values ('mesa', 0.42, 10);
insert into product (name, cost, min_priory) values ('tobo', 5.40, 11);
insert into product (name, cost, min_priory) values ('comedor', 7.67, 12);
insert into product (name, cost, min_priory) values ('ollas', 1.31, 13);
insert into product (name, cost, min_priory) values ('lavadora', 8.02, 14);
insert into product (name, cost, min_priory) values ('licuadora', 9.25, 15);
insert into product (name, cost, min_priory) values ('cama', 6.57, 16);
insert into product (name, cost, min_priory) values ('colchon', 6.97, 17);
insert into product (name, cost, min_priory) values ('vehiculo', 3.58, 18);
insert into product (name, cost, min_priory) values ('centro de mesa', 1.10, 19);
insert into product (name, cost, min_priory) values ('mesa de noche', 3.10, 20);

insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Tracey', 'Luscombe', 'vulputate', 'tluscombe0@gravatar.com', '2023-05-07', 1, '2027-11-21');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Wren', 'Haining', 'ut', 'whaining1@sitemeter.com', '2024-01-18', 3, '2023-09-11');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Cari', 'Milazzo', 'ligula', 'cmilazzo2@addtoany.com', '2024-01-03', 4, '2023-09-26');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Geno', 'Rosenstein', 'nisl', 'grosenstein3@wiley.com', '2023-10-28', 2, '2023-05-16');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Gertrude', 'Spere', 'amet', 'gspere4@163.com', '2023-08-02', 10, '2023-09-26');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Thorstein', 'Middlewick', 'nulla', 'tmiddlewick5@irs.gov', '2023-12-26', 4, '2023-10-24');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Jodi', 'Moxsom', 'felis', 'jmoxsom6@google.com.br', '2023-07-23', 6, '2023-09-05');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Mendel', 'Kidder', 'odio', 'mkidder7@live.com', '2023-09-30', 3, '2023-05-07');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Roxanna', 'Martyns', 'quam', 'rmartyns8@shutterfly.com', '2023-08-20', 9, '2024-02-05');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Cyndia', 'Kantor', 'lorem', 'ckantor9@skyrock.com', '2023-03-28', 10, '2023-10-23');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Tiebold', 'Hubbins', 'ullamcorper', 'thubbinsa@mac.com', '2023-08-05', 8, '2023-06-18');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Ronalda', 'Kiff', 'etiam', 'rkiffb@google.pl', '2023-12-20', 7, '2023-08-30');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Cindi', 'Sarle', 'varius', 'csarlec@ebay.com', '2024-01-28', 7, '2023-12-15');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Amerigo', 'Richardes', 'iaculis', 'arichardesd@bloomberg.com', '2023-06-28', 6, '2023-03-09');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Tierney', 'Dallison', 'praesent', 'tdallisone@cmu.edu', '2023-04-05', 5, '2024-01-26');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Fletcher', 'Dabell', 'libero', 'fdabellf@dion.ne.jp', '2023-08-06', 4, '2023-09-08');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Orlando', 'Gietz', 'at', 'ogietzg@w3.org', '2024-01-07', 10, '2023-07-13');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Alister', 'Kares', 'mauris', 'akaresh@w3.org', '2024-01-02', 1, '2023-03-09');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Mile', 'Flieger', 'leo', 'mfliegeri@hexun.com', '2024-02-18', 4,'2024-01-19');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Nahum', 'Ezzle', 'posuere', 'nezzlej@google.com.au', '2024-01-17', 9, '2023-03-22');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Kai', 'Kauble', 'nisi', 'kkaublek@altervista.org', '2023-06-26', 7, '2023-08-22');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Tanny', 'Pankettman', 'maecenas', 'tpankettmanl@economist.com', '2023-10-30', 10, '2023-03-27');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Kendra', 'Van Castele', 'venenatis', 'kvancastelem@ehow.com', '2023-07-08', 1, '2024-02-10');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Gun', 'Caldroni', 'nam', 'gcaldronin@timesonline.co.uk', '2023-04-23', 2, '2023-06-09');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Karine', 'Leopold', 'odiomm', 'kleopoldo@bbb.org', '2023-09-09', 5, '2024-01-18');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Wes', 'Sparrow', 'phasellus', 'wsparrowp@state.gov', '2023-03-21', 6, '2023-11-10');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Giffie', 'Grooby', 'auctor', 'ggroobyq@seesaa.net', '2023-11-26', 4, '2023-10-22');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Doreen', 'Doutch', 'justo', 'ddoutchr@forbes.com', '2023-04-30', 3, '2023-10-22');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Judith', 'Tweddle', 'quam', 'jtweddles@dailymail.co.uk', '2023-10-31', 1, '2023-09-22');
insert into client (name, lastname, dni, email, last_delivery, membership, next_renewal) values ('Ruthe', 'Freeburn', 'ultrices', 'rfreeburnt@homestead.com', '2023-07-29', 10, '2023-08-08');